apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-ai-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hakanbayraktar/news-summary-gke'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
