apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
