name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ☁️ Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          install_components: kubectl

      - name: 🔐 Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: ⚙️ Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GKE_REGION }}-docker.pkg.dev

      - name: 🔑 Get GKE credentials
        run: |
          gcloud container clusters get-credentials "${{ vars.GKE_CLUSTER_NAME }}" \
            --region "${{ vars.GKE_REGION }}" \
            --project "${{ vars.GCP_PROJECT_ID }}"

      - name: 🧱 Build and push Backend Docker image
        run: |
          docker build \
          --no-cache \
          -t ${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-backend:${{ env.IMAGE_TAG }} news-app
          docker push ${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-backend:${{ env.IMAGE_TAG }}

      - name: 🎨 Build and push Frontend Docker image
        run: |
          docker build \
            --no-cache \
            --build-arg VITE_API_URL=${{ vars.VITE_NEWS_API_URL }} \
            -t ${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-frontend:${{ env.IMAGE_TAG }} \
            news-app/frontend
          docker push ${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-frontend:${{ env.IMAGE_TAG }}

      - name: 📝 Update manifests with full image lines
        run: |
          sed -i "s|^\( *image: \).*news-backend.*|\\1${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-backend:${{ env.IMAGE_TAG }}|" manifests/deployment-backend.yaml
          sed -i "s|^\( *image: \).*news-frontend.*|\\1${{ vars.GKE_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/news-app/news-frontend:${{ env.IMAGE_TAG }}|" manifests/deployment-frontend.yaml

      - name: 📤 Commit and push manifest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment-*.yaml
          git commit -m "🚀 Update image tags to $IMAGE_TAG for ArgoCD auto-deploy" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git


